" .............................................................................
" vim-voom/voom
" .............................................................................
let g:voom_ft_modes = {'markdown': 'markdown', 'vimwiki': 'markdown'}
let g:voom_default_mode = 'markdown'
